"""
Django settings for Matrimony project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env_path = BASE_DIR / '.env'
load_dotenv(dotenv_path=env_path, override=True)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-&^h)=c30buy56uqt3x0m!esz&+de1p#5pw13a7i5)i)alw)5j+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = ['*']

# Fast2SMS Integration
FAST2SMS_API_KEY = os.environ.get('FAST2SMS_API_KEY', '')

# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'channels',
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts_app',
    'admin_panel',
    'interactions_app',
    'payments_app',
    'profiles_app',
    'website',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'cloudinary_storage',
    'cloudinary',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'profiles_app.middleware.UpdateLastActivityMiddleware',
    'admin_panel.middleware.MaintenanceModeMiddleware',
    'accounts_app.middleware.PremiumExpiryMiddleware',
]


ROOT_URLCONF = 'Matrimony.urls'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['Template'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'interactions_app.context_processors.navbar_badges',
                'interactions_app.context_processors.master_data',
                'website.context_processors.website_settings',
            ],
        },
    },
]

WSGI_APPLICATION = 'Matrimony.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        env='MYSQL_ADDON_URI',  # Clever Cloud MySQL uses this
        conn_max_age=0,
        conn_health_checks=True,
    )
}
# Fallback if MYSQL_ADDON_URI is not set and DATABASE_URL is set instead (e.g. Postgres)
if not os.environ.get('MYSQL_ADDON_URI') and os.environ.get('DATABASE_URL'):
    DATABASES['default'] = dj_database_url.config(default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}", conn_max_age=0)


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = ['static/']

# Cloudinary Setup for Media
import os
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

CLOUDINARY_STORAGE = {
    'CLOUD_NAME': 'czlrenm1',
    'API_KEY': '536361658649224',
    'API_SECRET': 'xK_cJv9Xon50i8I0Q-QtQedMkKk',
}
STORAGES = {
    "default": {
        "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}


AUTHENTICATION_BACKENDS = [
    'accounts_app.backends.EmailBackend',
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

SITE_ID = 1

DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'

ASGI_APPLICATION = 'Matrimony.asgi.application'

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    },
}

# Email Configuration (SMTP for real emails)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'foreverbond137@gmail.com'
EMAIL_HOST_PASSWORD = 'xrvsityzopgxxnxn'  # App Password without spaces
DEFAULT_FROM_EMAIL = 'foreverbond137@gmail.com'

# Strict Session Security for Admin Panel
SESSION_EXPIRE_AT_BROWSER_CLOSE = True


JAZZMIN_SETTINGS = {
    "site_title": "Matrimony Admin",
    "site_header": "ForeverBond",
    "site_brand": "ForeverBond Matrimony",
    "welcome_sign": "Welcome to ForeverBond Admin Panel",
    "copyright": "ForeverBond Matrimony",
    "show_ui_builder": False,
    "show_version": False,
    "topmenu_links": [
        {"name": "Home",  "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "View Live Website", "url": "/", "icon": "fas fa-globe"},
    ],
    "icons": {
        "auth.User": "fas fa-users-cog",
        "auth.Group": "fas fa-users",
        "profiles_app.Profile": "fas fa-id-card",
        "payments_app.Transaction": "fas fa-money-bill-wave",
        "payments_app.MembershipPlan": "fas fa-crown",
        "interactions_app.Chat": "fas fa-comments",
        "interactions_app.InterestRequest": "fas fa-heart",
        "account.EmailAddress": "fas fa-envelope-open-text",
    },
    "default_icon_parents": "fas fa-folder",
    "default_icon_children": "fas fa-circle",
    "related_modal_active": True,
    "custom_css": "css/custom_admin.css",
    "navigation_expanded": True,
}

JAZZMIN_UI_TWEAKS = {
    "theme": "flatly",
    "navbar": "navbar-white navbar-light",
    "sidebar": "sidebar-dark-danger",
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": True,
    "navbar_fixed": True,
    "sidebar_fixed": True,
    "button_classes": {
        "primary": "btn-danger",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}





STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
