# Generated by Django 4.2.23 on 2026-07-15 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interestrequest',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
