# Generated by Django 6.0.5 on 2026-07-16 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions_app', '0002_alter_interestrequest_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interestrequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
