# Generated by Django 6.0.5 on 2026-07-23 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions_app', '0005_savedprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='deleted_by_receiver',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='deleted_by_sender',
            field=models.BooleanField(default=False),
        ),
    ]
