# Generated by Django 6.0.5 on 2026-07-23 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions_app', '0007_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='interestrequest',
            name='is_viewed',
            field=models.BooleanField(default=False),
        ),
    ]
