# Generated by Django 6.0.5 on 2026-07-29 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CounselingQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('topic', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('admin_reply', models.TextField(blank=True, help_text="Type your reply here. Saving the model will automatically send this reply to the user's email.", null=True)),
                ('is_resolved', models.BooleanField(default=False)),
            ],
        ),
    ]
