# Generated by Django 6.0.5 on 2026-07-20 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_app', '0004_profile_about_me'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='blur_profile_photo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='email_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='hide_contact_info',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='sms_alerts',
            field=models.BooleanField(default=False),
        ),
    ]
