# Generated by Django 6.0.5 on 2026-07-20 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_app', '0005_profile_blur_profile_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_photo_approved',
            field=models.BooleanField(default=False),
        ),
    ]
