# Generated by Django 6.0.5 on 2026-07-23 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_app', '0008_profile_last_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='privacy_blur',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ProfileGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='gallery_photos/')),
                ('is_approved', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_photos', to='profiles_app.profile')),
            ],
        ),
    ]
