# Generated by Django 6.0.5 on 2026-07-29 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments_app', '0002_alter_membershipplan_id_alter_transaction_id'),
        ('profiles_app', '0012_alter_profile_approval_status_alter_profile_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='active_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_profiles', to='payments_app.membershipplan'),
        ),
        migrations.AddField(
            model_name='profile',
            name='interests_sent_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='plan_expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
